import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Bebas_Neue, Barlow } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { SeasonProvider } from "@/app/context/SeasonContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas",
  weight: "400",
  subsets: ["latin"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard - Umelka - 2025",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
    viewportFit: "cover"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-50 dark:bg-gray-950">
       <head>
           <meta name="mobile-web-app-capable" content="yes" />
           <meta
               name="apple-mobile-web-app-status-bar-style"
               content="black-translucent"
           />
       </head>
      <body
        className={`
          h-full
          bg-gray-50 dark:bg-gray-950
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${bebasNeue.variable} 
          ${barlow.variable} 
          antialiased`}
      >
            <SeasonProvider>
              <div className="flex h-[100dvh] flex-col">
                {children}
              </div>
            </SeasonProvider>
        <Analytics />
      </body>
    </html>
  );
}
