import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { SeasonProvider } from "@/app/context/SeasonContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard - Umelka - 2025",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
    viewportFit: "cover"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
           <meta name="apple-mobile-web-app-capable" content="yes" />
           <meta
               name="apple-mobile-web-app-status-bar-style"
               content="black-translucent"
           />
       </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <SeasonProvider>
                {children}
            </SeasonProvider>
        <Analytics />
      </body>
    </html>
  );
}
